# Generated by Django 5.2.7 on 2026-08-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_company_name_post_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.BigIntegerField(),
        ),
    ]
